# Generated by Django 5.2.12 on 2026-04-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_guestprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('DR', 'Dr.'), ('PROF', 'Prof.')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='place_of_issue',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='visa_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
