# Generated by Django 5.2.12 on 2026-04-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_sample_guests'),
        ('accounts', '0003_guestprofile_designation_guestprofile_first_name_and_more'),
    ]

    operations = [
    ]
