# Generated by Django 5.2.12 on 2026-04-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_actual_check_in_booking_actual_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coming_from',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='extra_bed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_type',
            field=models.CharField(blank=True, choices=[('FIT', 'FIT (Free Individual Traveler)'), ('GROUP', 'Group'), ('CORPORATE', 'Corporate'), ('VIP', 'VIP'), ('GOVERNMENT', 'Government'), ('DIPLOMATIC', 'Diplomatic')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='offer_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='purpose_of_visit',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='rack_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='registration_card',
            field=models.ImageField(blank=True, null=True, upload_to='registration_cards/'),
        ),
    ]
