# Generated by Django 5.2.12 on 2026-04-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_coming_from_booking_extra_bed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='infants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
