# Generated by Django 5.2.12 on 2026-04-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_create_sample_bookings'),
        ('bookings', '0004_add_infants_contact_person'),
    ]

    operations = [
    ]
