# Generated by Django 5.2.12 on 2026-04-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_add_infants_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_tran_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_brand',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_issuer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_issuer_country',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_no',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, default='BDT', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='risk_level',
            field=models.CharField(blank=True, default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='risk_title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='store_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='val_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
