# Generated by Django 5.2.12 on 2026-04-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_payment_status_payment_bank_tran_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=100)),
                ('store_password', models.CharField(max_length=255)),
                ('is_sandbox', models.BooleanField(default=True)),
                ('frontend_url', models.CharField(default='http://localhost:5173', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable online payment gateway')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway Config',
                'verbose_name_plural': 'Payment Gateway Config',
            },
        ),
    ]
