# Generated by Django 5.2.12 on 2026-04-01 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_merge_20260402_0307'),
        ('bookings', '0006_payment_gateway_config'),
    ]

    operations = [
    ]
