# Generated by Django 5.2.12 on 2026-04-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='housekeeping_status',
            field=models.CharField(choices=[('CLEAN', 'Clean'), ('DIRTY', 'Dirty'), ('INSPECTED', 'Inspected'), ('OUT_OF_ORDER', 'Out of Order')], default='CLEAN', max_length=15),
        ),
        migrations.AddField(
            model_name='room',
            name='is_smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='last_cleaned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
