# Generated by Django 5.2.12 on 2026-04-01 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NightAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField(unique=True)),
                ('total_rooms_sold', models.PositiveIntegerField(default=0)),
                ('total_rooms_available', models.PositiveIntegerField(default=0)),
                ('occupancy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('room_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fnb_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('no_show_count', models.PositiveIntegerField(default=0)),
                ('new_bookings', models.PositiveIntegerField(default=0)),
                ('check_ins', models.PositiveIntegerField(default=0)),
                ('check_outs', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-audit_date'],
            },
        ),
    ]
